image: golang:1.11
stages:
  - build
  - test

before_script:
  - cp -r /builds/user /go/src/github.com/user/
  - cd /go/src/github.com/user/repo

build-my-project:
  stage: build
  script:
    - go get -v ./...

test-my-project:
  stage: test
  script:
    - go test -v ./...
